### ISSUE TITLE
Is it normal for white text on a black background to appear in the image?

### ISSUE THREAD

**Issue by typeface-cn** [clovaai/fewshot-font-generation#10]
Use the MX-Font. The source image is black on white. But result/mx/images/last.png is like this:
![last](https://user-images.githubusercontent.com/16305284/187030611-de2469f4-3891-4c0e-bdd3-0367e3014bdb.png)

**Comment by 8uos** [comment]
Hello, sorry for the late reply.

It is weird... I think it is related to the Pillow version.
I will check the code. 
If available, please provide me the font file of black background images. It would be a big help to me.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
