### ISSUE TITLE
Can I get a trained model for korean?

### ISSUE THREAD

**Issue by jihong-yu** [clovaai/fewshot-font-generation#11]
Hello, I trained 98 korean fonts more than 100,000 times. If I try to convert my own handwriting into letters, the recognition rate drops considerably. If there is a great model that has already been trained, can I get it for the test?

**Comment by SanghyukChun** [comment]
We are not going to provide any weight based on this repository.
However, you can check weights from our previous project:

- https://github.com/clovaai/lffont/tree/master/weight

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
