### ISSUE TITLE
About Training Weights

### ISSUE THREAD

**Issue by awei669** [clovaai/fewshot-font-generation#12]
Can you provide the pre training weights of several methods of repo on the Chinese dataset?

**Comment by SanghyukChun** [comment]
We are not going to provide any weight based on this repository.
However, you can check weights from our previous repositories:

- https://github.com/clovaai/lffont/tree/master/weight
- https://github.com/clovaai/mxfont/blob/main/generator.pth

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
