### ISSUE TITLE
Finding it difficult to get started

### ISSUE THREAD

**Issue by yomismith** [clovaai/fewshot-font-generation#13]
Hi, I'm finding it hard to get started, The problem  is the config part for the training part, which is highlighted as no 1 for getting started for the training section please help, and Thanks for giving me the opportunity being able to become a Machine learning beginer

**Comment by SanghyukChun** [comment]
Please read the documents carefully first.
https://github.com/clovaai/fewshot-font-generation/tree/main/docs

FUNIT is the simplest method, so it could be a good starting point
https://github.com/clovaai/fewshot-font-generation/blob/main/docs/models/FUNIT.md

If you have any other problem not included in the documents, please open another issue.
