### ISSUE TITLE
the requirement of the font

### ISSUE THREAD

**Issue by simbadu1999** [clovaai/fewshot-font-generation#4]
Is it necessary that the font I use must be a true type or an open type one? There is an error when I input a font made by other organizations into the get_chars_from_ttfs.py.

**Comment by simbadu1999** [comment]
ps： the font I use is "xxxx.TTF" and there is a mistake, too. Is that illegal? THANKS!

**Comment by 8uos** [comment]
Our code only treats '.ttf' files (ttf should be lower cases!).
If you still have problems after changing "TTF" to "ttf", please show the error message to me.
Thanks!

**Comment by simbadu1999** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是杜承豪，已收到您的邮件，谢谢啦，我会尽快给您回复。

**Comment by simbadu1999** [comment]
> Our code only treats '.ttf' files (ttf should be lower cases!). If you still have problems after changing "TTF" to "ttf", please show the error message to me. Thanks!

![1643100084(1)](https://user-images.githubusercontent.com/52853110/150941995-e4aa97e0-53b5-42e0-bf94-a9a618ba1f74.png)

**Comment by simbadu1999** [comment]
> Our code only treats '.ttf' files (ttf should be lower cases!). If you still have problems after changing "TTF" to "ttf", please show the error message to me. Thanks!

I found that my own ttf.sfontversion is #$ as shown in pic1, while your given ttf is [] as shown in pic2.
![1643100607(1)](https://user-images.githubusercontent.com/52853110/150943415-3630e6ba-3dd6-447c-9904-c1ab08f57864.png)
![1643100818(1)](https://user-images.githubusercontent.com/52853110/150944007-e56afa0c-f852-48bf-8f3a-039046e41938.png)

**Comment by simbadu1999** [comment]
To correct the description above, the given ttf's sfontversion is "\x00\x01\x00\x00" ,which equals to"  ". Thus, the code judges the sentence is false and didn't raise the error, while my ttf's sfontversion is not in  ("\x00\x01\x00\x00", "OTTO", "true"). So, may I delete the judgement sentence? THANKS!

**Comment by simbadu1999** [comment]
btw, what's the meaning of calculating the means of the rendered picture? Thank you very much!
![1643101829(1)](https://user-images.githubusercontent.com/52853110/150946764-c7d5a77d-19d5-4000-98cd-5b769f545652.png)

**Comment by 8uos** [comment]
> > Our code only treats '.ttf' files (ttf should be lower cases!). If you still have problems after changing "TTF" to "ttf", please show the error message to me. Thanks!
> 
> I found that my own ttf.sfontversion is #$ as shown in pic1, while your given ttf is [] as shown in pic2. ![1643100607(1)](https://user-images.githubusercontent.com/52853110/150943415-3630e6ba-3dd6-447c-9904-c1ab08f57864.png) ![1643100818(1)](https://user-images.githubusercontent.com/52853110/150944007-e56afa0c-f852-48bf-8f3a-039046e41938.png)

Actually, I don't know well about the .ttf files, but the code I uploaded worked well for my font files.
If you can define the available character list from the ttf file with your own method, it is okay to use that method.
Please see [here](https://github.com/clovaai/fewshot-font-generation/blob/main/data_example/chn/ttf/MaShanZheng-Regular.txt) for the example.

**Comment by simbadu1999** [comment]
> > > Our code only treats '.ttf' files (ttf should be lower cases!). If you still have problems after changing "TTF" to "ttf", please show the error message to me. Thanks!
> > 
> > 
> > I found that my own ttf.sfontversion is #$ as shown in pic1, while your given ttf is [] as shown in pic2. ![1643100607(1)](https://user-images.githubusercontent.com/52853110/150943415-3630e6ba-3dd6-447c-9904-c1ab08f57864.png) ![1643100818(1)](https://user-images.githubusercontent.com/52853110/150944007-e56afa0c-f852-48bf-8f3a-039046e41938.png)
> 
> 1. Actually, I don't know well about the .ttf files, but the code I uploaded worked well for my font files.
>    If you can define the available character list from the ttf file with your own method, it is okay to use that method.
>    Please see [here](https://github.com/clovaai/fewshot-font-generation/blob/main/data_example/chn/ttf/MaShanZheng-Regular.txt) for the example.
> 2. I checked the mean of the rendered picture to filter blank images because there were some characters with blank images in my font files.

got it, thanks！

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.

**Comment by simbadu1999** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我是杜承豪，已收到您的邮件，谢谢啦，我会尽快给您回复。
