### ISSUE TITLE
Use the MX-Font. How to set source_path in cfgs/data/train/custom.yaml?

### ISSUE THREAD

**Issue by typeface-cn** [clovaai/fewshot-font-generation#9]
What are unseen_chars and seen_chars? What is the difference between source_path and data_dir? thanks

**Comment by 8uos** [comment]
Hi, sorry for the late reply. 

"seen_chars" is a list of characters to be used for the training, and "unseen_chars" is a list of characters to exclude during the training.
"source_path" is the path to your source font file, and "data_dir" is the path to the directory style fonts for training are saved.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
